version: '3.8'

services:
  data-ingestion:
    image: data-ingestion
    build:
      context: ./data_ingestion
      dockerfile: Dockerfile
    networks:
      - job-network
    ports:
      - "3000:8000"
    volumes:
      - ./data_ingestion:/app
    depends_on:
      - milvus-standalone
      - embedding-service

  embedding-service:
    image: embedding-service
    build:
      context: ./embeddings
      dockerfile: Dockerfile
    networks:
      - job-network
    ports:
      - "8001:8000"
    volumes:
      - ./embeddings:/app
    depends_on:
      - milvus-standalone
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - job-network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/minio:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - job-network

  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.1
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    entrypoint: ["/tini", "--"]
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio
    networks:
      - job-network

networks:
  job-network:
    driver: bridge